# Generated by Django 2.1.5 on 2019-02-09 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Textpage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Page title')),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('text', models.TextField(blank=True, verbose_name='Text of the page')),
            ],
        ),
    ]
