# Generated by Django 2.1.5 on 2019-02-11 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_auto_20190211_2204'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='show',
            field=models.BooleanField(default=True),
        ),
    ]
